### ISSUE TITLE
bwrap bind /bin hides system's git on /usr merge distributions

### ISSUE THREAD

**Issue by PkmX** [DavHau/nix-portable#11]
On distributions with UsrMerge like Arch Linux, `/bin` is a symlink to `/usr/bin`. If git is already installed, nix-portable will find it at `/usr/bin/git` and sets `needGit` to false. Then it proceeds to bind `${busybox}/bin` to `/bin`, which actually binds to `/usr/bin` and hides the host's git binary. Executing any `nix` command that requires git now results in:

```
executing 'git': No such file or directory
```

There are multiple ways to fix, maybe just don't bind `${busybox}/bin` but prepends it to `PATH`? Or perhaps it doesn't even need to bring its own busybox, just assume the system's coreutils, tar, xz as dependencies which should be available on almost every system.

**Comment by DavHau** [comment]
Oh, busybox should definitely not be mounted to /bin.

I would really like to not depend on the system providing tar  and xz.
Maybe it would be best to just append busybox to PATH? I guess there shouldn't be any situations where this breaks anything.

**Comment by PkmX** [comment]
I think not binding busybox and just prepending its store path to PATH is the easiest fix.

**Comment by DavHau** [comment]
Should be fixed on master. Could you check again?

**Comment by PkmX** [comment]
Works fine here now!
