### ISSUE TITLE
transfer to nix-community 

### ISSUE THREAD

**Issue by Artturin** [DavHau/nix-portable#40]
It's a cool project and it'd be nice if there were more maintainers

(I can be a co-maintainer if it's ok with you)

**Comment by dnkmmr69420** [comment]
this is a good idea. this should happen

**Comment by DavHau** [comment]
For now I'd like to keep it under my profile.

I'm happy to add more maintainers to the project at any time, if there is someone who qualifies for it, which means they contribute to the project frequently and are familiar with it.

Currently there aren't many contributions to the project in general, so I don't see who would qualify as a maintainer.
Given the little number of contributions, having only a single maintainer is also not a bottleneck.

Before the project needs maintainers it needs contributions and anyone is invited at any time to do them.
