### ISSUE TITLE
Debugging 'unzip: short read'

### ISSUE THREAD

**Issue by jacg** [DavHau/nix-portable#81]
Trying to use `nix-portable` on an (idiosyncratic ... but aren't they all!) HPC system, I get the following error:
```
$ ./nix-portable run nixpkgs#cowsay -- hello
unzip: short read
```
How should I go about understanding what it causing it?

I see that the timestamp on `.nix-portable/tmpbin` is updated whenever I run the above command, but the directory is empty, so I can't immediately check my hypothesis that `nix-portable` is trying to download and unzip a resource, but is getting an error message instead of the resource.

**Comment by DavHau** [comment]
Maybe your nix-portable is corrupt? You could re-download it on another machine and compare hashes.

**Comment by jacg** [comment]
Indeed. For some reason the whole file is never fully downloaded into my home directory. (Seems to be a disk quota issue, even though I seem to have almost 2 TB of quota left). When I download it into `/tmp` and point `NP_LOCATION` there too, it seems to work fine.

Thanks for the hint.
